#### https://www.youtube.com/watch?v=PHxYNGo8NcI

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('salaries.csv')

In [4]:
df.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [5]:
df['company_encoded'] = LabelEncoder().fit_transform(df['company'])

In [6]:
df['job_encoded'] = LabelEncoder().fit_transform(df['job'])

In [7]:
df['degree_encoded'] = LabelEncoder().fit_transform(df['degree'])

In [8]:
df.head()

company                  job     degree  salary_more_then_100k  \
0  google      sales executive  bachelors                      0   
1  google      sales executive    masters                      0   
2  google     business manager  bachelors                      1   
3  google     business manager    masters                      1   
4  google  computer programmer  bachelors                      0   

   company_encoded  job_encoded  degree_encoded  
0                2            2               0  
1                2            2               1  
2                2            0               0  
3                2            0               1  
4                2            1               0

In [9]:
df.drop(['company', 'job', 'degree'], axis='columns', inplace=True)

In [10]:
df.head()

salary_more_then_100k  company_encoded  job_encoded  degree_encoded
0                      0                2            2               0
1                      0                2            2               1
2                      1                2            0               0
3                      1                2            0               1
4                      0                2            1               0

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
model = DecisionTreeClassifier()

In [14]:
model.fit(df[['company_encoded', 'job_encoded', 'degree_encoded']], df[['salary_more_then_100k']])

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [15]:
model.predict([[1, 1, 1]]) # making predictions

array([1], dtype=int64)

In [20]:
model.predict([[0, 1, 0]]) # making predictions

array([0], dtype=int64)

#### https://www.youtube.com/watch?v=Rz-tZXYQ36M

In [21]:
from sklearn.datasets import load_iris

In [22]:
iris = load_iris()

In [23]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [24]:
iris.target[0]

0

In [30]:
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [31]:
model.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [32]:
y_predicted = model.predict(x_test)

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_predicted, y_test)

0.9333333333333333